<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-02-19 23:05

$extensionPath = t3lib_extMgm::extPath('themes_adapter_templavoilaframework');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_themesadaptertemplavoilaframework_domain_model_skin' => $extensionClassesPath . 'Domain/Model/Skin.php',
	'tx_themesadaptertemplavoilaframework_hooks_tx_themes_domain_repository_skinrepository_hook' => $extensionClassesPath . 'Hooks/Tx_Themes_Domain_Repository_SkinRepository_Hook.php',
);
?>